apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: samba
spec:
  type: NodePort
  ports:
    - name: netbios-ssn
      port: 139
      targetPort: 139
      nodePort: 30139
    - name: microsoft-ds
      port: 445
      targetPort: 445
      nodePort: 30445
    - name: netbios-ns
      port: 137
      targetPort: 137
      nodePort: 30137
      protocol: UDP
    - name: netbios-dgm
      port: 138
      targetPort: 138
      nodePort: 30138
      protocol: UDP
  selector:
    app: samba

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - image: jpmenegatti/samba:v5
        name: samba
        ports:
          - containerPort: 139
            name: netbios-ssn
          - containerPort: 445
            name: microsoft-ds
          - containerPort: 137
            name: netbios-ns
            protocol: UDP
          - containerPort: 138
            name: netbios-dgm
            protocol: UDP
        volumeMounts:
        - name: samba-persistent-storage
          mountPath: /mnt
        args: [ '-s  volume1;/mnt;yes;no;yes;all;none -s volume2;/mnt;yes;no;no;jpmenega;jpmenega' ]
      volumes:
      - name: samba-persistent-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: volume-samba
          readOnly: false
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
