- hosts: all
  become: yes
  tasks:
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}.{{ domain_name }} {{item}}" state=present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups['all'] }}"

    - name: "Install zabbix-agent"
      apt:
       name: zabbix-agent
       state: present
       update_cache: true

    - name: "Configure Zabbix Agent"
      copy:
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: u=rw,g=r,o=r
        owner: zabbix
        content: |
            LogFile=/tmp/zabbix_agentd.log
            Server=192.168.1.252,192.168.1.243,192.168.1.244
            Include=/etc/zabbix/zabbix_agentd.conf.d/
            Hostname={{ ansible_hostname }}

    - name: gluster-monitoring.pl
      shell: "wget https://raw.githubusercontent.com/jpmenega/kubernetes/main/main/zabbix-agent/gluster-monitoring.pl"
      args:
        chdir: /etc/zabbix
        creates: gluster-monitoring.pl
      when: gluster == "yes"
      with_items: "{{ gluster | default([]) }}"

    - name: "gluster-monitoring.pl permission"
      file:
        path: /etc/zabbix/gluster-monitoring.pl
        state: touch
        mode: u=rwx,g=rx,o=rx
      when: gluster == "yes"
      with_items: "{{ gluster | default([]) }}"

    - name: gluster.conf
      shell: "wget https://raw.githubusercontent.com/jpmenega/kubernetes/main/main/zabbix-agent/gluster.conf"
      args:
        chdir: /etc/zabbix/zabbix_agentd.conf.d
        creates: gluster.conf
      when: gluster == "yes"
      with_items: "{{ gluster | default([]) }}"

    - name: zabbix sudoer
      shell: "wget https://raw.githubusercontent.com/jpmenega/kubernetes/main/main/zabbix-agent/zabbix"
      args:
        chdir: /etc/sudoers.d/
        creates: zabbix
      when: gluster == "yes"
      with_items: "{{ gluster | default([]) }}"

    - name: "Install libswitch-perl"
      apt:
       name: libswitch-perl
       state: present
       update_cache: true
      when: gluster == "yes"
      with_items: "{{ gluster | default([]) }}"

    - name: Restart zabbix-agent
      service:
        name: zabbix-agent.service
        state: restarted
