apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  namespace: zabbix
spec:
  ports:
    - port: 10050
  selector:
    app: zabbix-agent
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      containers:
      - image: zabbix/zabbix-agent:alpine-5.2-latest
        name: zabbix-agent
        env:
        - name: ZBX_SERVER_HOST
          value: 192.168.1.0/24,10.0.0.0/8
          #value: zabbix-server
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_HOSTNAMEITEM
          value: system.hostname
        ports:
        - containerPort: 10049
          name: zabbix-agent
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        securityContext:
          privileged: true
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
