apiVersion: v1
kind: Service
metadata:
  name: fs-client
  namespace: zabbix
spec:
  ports:
    - port: 80
  selector:
    app: fs-client
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-client
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fs-client
    spec:
      containers:
      - image: jpmenegatti/fssupport:v2
        name: fs-client
        ports:
        - containerPort: 80
        #command: ["bash", "-c", "/'docker-entrypoint.sh'"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /mnt/infra
      volumes:
      - name: mysql-persistent-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: volume-infra
          readOnly: false
