apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-apache
  namespace: zabbix
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: zabbix-web-apache
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-apache
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web-apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zabbix-web-apache
    spec:
      containers:
      - image: zabbix/zabbix-web-apache-mysql:alpine-5.2-latest
        name: zabbix-web-apache
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: MYSQL_DATABASE
          value: zabbix
        - name: ZBX_SERVER_NAME
          value: Composed installation
        - name: PHP_TZ
          value: America/Sao_Paulo
        ports:
        - containerPort: 8080
          name: zabbix-web-apache-http
        - containerPort: 8443
          name: zabbix-web-apache-https
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
