apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  ports:
    - port: 10051
  selector:
    app: zabbix-server
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - image: zabbix/zabbix-server-mysql:alpine-5.2-latest
        name: zabbix-server
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: MYSQL_DATABASE
          value: zabbix
        ports:
        - containerPort: 10051
          name: zabbix-server
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
