apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  namespace: zabbix
spec:
  containers:
  - name: mysql-server
    image: mysql:8.0
    volumeMounts:
    - mountPath: "/var/lib/mysql"
      name: glusterfsvol-mysql
    securityContext:
      privileged: true
  volumes:
  - name: glusterfsvol-mysql
    glusterfs:
      endpoints: glusterfs-cluster
      path: volume-infra/zabbix/var/lib/mysql
      readOnly: false
