apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
  namespace: zabbix
spec:
  containers:
  - name: glusterfs
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/glusterfs"
      name: glusterfsvol
    securityContext:
      privileged: true
  volumes:
  - name: glusterfsvol
    glusterfs:
      endpoints: glusterfs-cluster
      path: volume-infra
      readOnly: false
