- hosts: all
  become: yes
  tasks:
   - name: install software-properties-common
     apt:
       name: software-properties-common
       state: present
       update_cache: true
     when: gluster == "yes"
     with_items: "{{ gluster | default([]) }}"

   - name: Add Gluster repository from PPA
     apt_repository:
       repo: 'ppa:gluster/glusterfs-8'
       state: present
     when: gluster == "yes"
     with_items: "{{ gluster | default([]) }}"

   - name: install glusterfs-server
     apt:
       name: glusterfs-server
       state: present
     when: gluster == "yes"
     with_items: "{{ gluster | default([]) }}"
   
   - name: Start Gluster
     service:
       name: glusterd.service
       state: started
     when: gluster == "yes"
     with_items: "{{ gluster | default([]) }}"

   - name: Enable service Gluster
     service:
       name: glusterd.service
       enabled: yes
     when: gluster == "yes"
     with_items: "{{ gluster | default([]) }}"

   #- name: "Build hosts file - Gluster"
   #  lineinfile: dest=/etc/hosts regexp='.*{{ hostvars[item].gluster_hostname }}$' line="{{ hostvars[item].ansible_host }} {{ hostvars[item].gluster_hostname }}" state=present
   #  when: hostvars[item].gluster_hostname is defined
   #  with_items: "{{ groups['all'] }}"

   #- name: install glusterfs-client
   #  apt:
   #    name: glusterfs-client
   #    state: present

- hosts: all
  become: yes
  tasks:
    - name: Gluster Probe
      shell: "gluster peer probe {{ ansible_hostname }} > probe-{{ ansible_hostname }}.txt"
      args:
        chdir: $HOME
        creates: probe-{{ ansible_hostname }}.txt
      delegate_to: ubuntu-masternode01
      when: gluster == "yes" and lb_slave == "yes"
      with_items: "{{ (gluster | default([])) and (lb_slave | default([])) }}"

    - name: Create volume
      shell: "gluster volume create volume-infra replica 3 ubuntu-masternode01:/gfs/infra ubuntu-masternode02:/gfs/infra ubuntu-masternode03:/gfs/infra force > volume-infra.txt"
      args:
        chdir: $HOME
        creates: volume-infra.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

- hosts: workers
  become: yes
  tasks:
    - name: Create volume
      shell: "gluster volume create volume-infra replica 2 ubuntu-workernode01:/gfs/infra ubuntu-workernode02:/gfs/infra force > volume-infra.txt"
      args:
        chdir: $HOME
        creates: volume-infra.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"


- hosts: all
  become: yes
  tasks:
    - name: Start volume
      shell: "gluster volume start volume-infra > start_volume.txt"
      args:
        chdir: $HOME
        creates: start_volume.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"
