apiVersion: v1
kind: Service
metadata:
  name: samba-fs
  namespace: glusterfs
spec:
  ports:
    - port: 80
  selector:
    app: samba-fs
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-fs
  namespace: glusterfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-fs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samba-fs
    spec:
      containers:
      - image: nginx
        name: samba-fs
        ports:
        - containerPort: 80
        #command: ["bash", "-c", "/'docker-entrypoint.sh'"]
        volumeMounts:
        - name: samba-persistent-storage
          mountPath: /mnt/samba
      volumes:
      - name: samba-persistent-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: volume-samba
          readOnly: false
