- hosts: ubuntu-masternode01
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: get key
      shell: kubeadm certs certificate-key
      register: join_key_raw

    - name: upload new certificate and key
      shell: kubeadm init phase upload-certs --upload-certs --certificate-key {{ join_key_raw.stdout_lines[0] }}

    - name: set key
      set_fact:
        join_key: "{{ join_key_raw.stdout_lines[0] }}"

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }} --certificate-key {{ join_key_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['ubuntu-masternode01'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
