apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: ldap
spec:
  type: NodePort
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      nodePort: 30389
    - name: ldap-s
      port: 636
      targetPort: 636
      nodePort: 30636
  selector:
    app: ldap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - image: jpmenegatti/ldap:v3
        name: ldap
        ports:
          - containerPort: 389
            name: ldap
          - containerPort: 636
            name: ldaps
        volumeMounts:
        - name: ldap-persistent-storage
          mountPath: /var/lib/openldap/openldap-data
      volumes:
      - name: ldap-persistent-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: volume-infra/openldap-data
          readOnly: false
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
