- hosts: ubuntu-masternode01
  become: yes
  become_user: ubuntu
  tasks:
    - name: create namespace
      shell: "kubectl apply -f https://raw.githubusercontent.com/jpmenega/kubernetes/main/ldap/ldap-ns.yaml > lpad-ns.txt"
      args:
        chdir: $HOME
        creates: ldap-ns.txt

    - name: create glusterfs-endpoints
      shell: "kubectl apply -f https://raw.githubusercontent.com/jpmenega/kubernetes/main/ldap/glusterfs-endpoints.yaml > ldap-gluster-endpoints.txt"
      args:
        chdir: $HOME
        creates: ldap-gluster-endpoints.txt
      when: notaint == "yes"
      with_items: "{{ notaint | default([]) }}"

    - name: create glusterfs-endpoints (taint)
      shell: "kubectl apply -f https://raw.githubusercontent.com/jpmenega/kubernetes/main/ldap/glusterfs-endpoints-taint.yaml > ldap-gluster-endpoints-taint.txt"
      args:
        chdir: $HOME
        creates: ldap-gluster-endpoints-taint.txt
      when: taint == "yes"
      with_items: "{{ taint | default([]) }}"

    - name: create glusterfs-service
      shell: "kubectl apply -f https://raw.githubusercontent.com/jpmenega/kubernetes/main/ldap/glusterfs-service.yaml > ldap-gluster-service.txt"
      args:
        chdir: $HOME
        creates: ldap-gluster-service.txt

    - name: create ldap server
      shell: "kubectl apply -f https://raw.githubusercontent.com/jpmenega/kubernetes/main/ldap/ldap.yaml > ldap.txt"
      args:
        chdir: $HOME
        creates: ldap.txt
